# Generated by Django 4.2.3 on 2023-07-30 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suggestions_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="state",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="city", name="country", field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="city", name="lat", field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="city", name="lon", field=models.FloatField(),
        ),
    ]
