# Generated by Django 4.2.3 on 2023-07-30 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "suggestions_app",
            "0002_city_state_alter_city_country_alter_city_lat_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(model_name="city", name="state",),
    ]
